#previewsEnabled: true
#previewsExpireAfterDays: 1
services:
- type: web
  autoDeploy: true
  pullRequestPreviewsEnabled: true
  initialDeployHook: ./dephook.sh
  name: simple-sinatra
  env: ruby
  healthCheckPath: /health
  buildCommand: ./build.sh
  startCommand: ./run.sh
databases:
  - name: testcustom
  - plan: Custom 8 CPU / 8GB RAM / 256GB SSD
