previewsEnabled: true
services:
- type: web
  autoDeploy: true
  plan: Custom 8 CPU / 16 GB RAM
  initialDeployHook: ./dephook.sh
  ##previewPlan: free
  name: simple-sinatra-blueprint
  env: ruby
  healthCheckPath: /api/utility/health
  rootDir: sin
  envVars:
  - key: PORT
    value: 9292
  - key: test_env
    sync: false
  buildCommand: ./build.sh
  startCommand: ./run.sh
#databases:
#- name: matdb
