previewsEnabled: true
services:
- type: web
  plan: free
  name: simple-sinatra-blueprint
  env: ruby
  healthCheckPath: /api/utility/health
  rootDir: sin
  envVars:
  - key: PORT
    value: 9292
  - key: test_env
    sync: false
  buildCommand: bundle install
  startCommand: bundle exec puma
databases:
- name: matdb
  plan: free
