previewsEnabled: true
#previewsExpireAfterDays: 1
services:
- type: web
  autoDeploy: true
  region: ohio
  ##plan: starter plus
  initialDeployHook: ./dephook.sh
  name: simple-sinatra-oh
  env: ruby
  healthCheckPath: /health
  buildCommand: ./build.sh
  startCommand: ./run.sh
  envVars:
    - fromGroup: auth
