previewsEnabled: true
previewsExpireAfterDays: 1
services:
- type: web
  repo: https://github.com/mmaddex/simple-sinatra.git
  branch: test-branch
  autoDeploy: true
  plan: starter
  ##initialDeployHook: ./dephook.sh
  previewPlan: Starter Plus
  name: simple-sinatra-blueprint-separatae
  env: ruby
  healthCheckPath: /api/utility/health
  buildCommand: ./build.sh
  startCommand: ./run.sh
