previewsEnabled: true
previewsExpireAfterDays: 1
services:
- type: web
  autoDeploy: true
  plan: starter
  ##initialDeployHook: ./dephook.sh
  previewPlan: Starter Plus
  name: simple-sinatra-blueprint-separatae
  env: ruby
  healthCheckPath: /health
  buildCommand: ./build.sh
  startCommand: ./run.sh
